Created class for command utilities and updated pom.xml
Dacaspex/Hansque pull request #3
Opened 2018-12-28 13:39 UTC by Dacaspex

### What is this?
Refactored part of the code that is responsible for parsing command strings. Created a static utility class for this. 

Added Sonar to the pom.xml for coverage reports from JUnit.

2018-12-28 14:56 UTC, Dacaspex commented
Possible wrong configuration, see https://stackoverflow.com/questions/45573102/sonarcloud-failure-with-travis-maven-github

2019-01-01 14:50 UTC, Dacaspex commented
Please use the "Squash and commit" merge strategy

2019-01-01 15:29 UTC, Extremelyd1 requested changes

2019-01-01 15:29 UTC, Extremelyd1 commented on src/main/java/com/hansque/commands/CommandStringUtil.java
> +            throw new IllegalArgumentException("The command string must contain at least one colon to identify the ");
Unfinished sentence?

2019-01-01 15:30 UTC, Dacaspex commented on src/main/java/com/hansque/commands/CommandStringUtil.java
> +            throw new IllegalArgumentException("The command string must contain at least one colon to identify the ");
Fixed

2019-01-01 15:31 UTC, Extremelyd1 approved these changes

2019-01-01 15:31 UTC, merged